#!/usr/bin/env python3
"""Samples an animated GIF onto the hexa's 271-pixel hex grid and emits
src/rickroll_data.h for the RickRoll pattern (see patterns.h).

Replicates ledgraph.h's exact AxialAccess pixel-index<->(q,r) mapping and
hexToRect formula so the sampled positions line up with the real firmware
pixel order, then averages a small patch of source pixels around each
mapped point per frame (271 pixels can't resolve a few-hundred-pixel source
image 1:1, so a patch average reads far cleaner than nearest-neighbor).

Requires Pillow: pip install Pillow (or use a venv).

Usage: python3 scripts/convert_gif.py [path/to/source.gif]
       (defaults to rik.gif in the project root)
"""
import math
import os
import sys
from PIL import Image, ImageSequence

MERIDIAN = 19
N = MERIDIAN // 2  # 9
LED_COUNT = 271

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GIF_PATH = sys.argv[1] if len(sys.argv) > 1 else os.path.join(PROJECT_ROOT, "rik.gif")
OUT_PATH = os.path.join(PROJECT_ROOT, "src", "rickroll_data.h")

# --- Replicate AxialAccess's exact pixel-index <-> (q,r) mapping (ledgraph.h) ---
# for r in -n..n: zigzag row order (right-to-left on odd "row" = r+n)
pixel_to_qr = [None] * LED_COUNT
px = 0
for r in range(-N, N + 1):
    q_start = max(-N, -N - r)
    q_end = min(N, N - r)
    row = r + N
    right_to_left = (row % 2) == 1
    qs = range(q_end, q_start - 1, -1) if right_to_left else range(q_start, q_end + 1)
    for q in qs:
        pixel_to_qr[px] = (q, r)
        px += 1
assert px == LED_COUNT, f"expected {LED_COUNT} pixels, got {px}"

SQRT3_2 = math.sqrt(3) / 2

def hex_to_rect(q, r):
    # matches ledgraph.h's AxialAccess::hexToRect with size=1
    x = q + 0.5 * r
    y = -SQRT3_2 * r
    return x, y

rect_positions = [hex_to_rect(q, r) for (q, r) in pixel_to_qr]
X_HALF, Y_HALF = 9.0, N * SQRT3_2  # ~9, ~7.79

# --- Load gif, sample each frame at each hex pixel's mapped image region ---
im = Image.open(GIF_PATH)
frames_rgb = [f.convert("RGB") for f in ImageSequence.Iterator(im)]
frame_count = len(frames_rgb)
img_w, img_h = frames_rgb[0].size

# patch half-size in source-image pixels, matching hex pixel pitch
patch_hw = max(1, int((img_w / (2 * X_HALF)) * 0.55))
patch_hh = max(1, int((img_h / (2 * Y_HALF)) * 0.55))

def map_to_image(x_rect, y_rect):
    ix = (x_rect + X_HALF) / (2 * X_HALF) * img_w
    iy = (1.0 - (y_rect + Y_HALF) / (2 * Y_HALF)) * img_h
    return ix, iy

def average_patch(pixels, cx, cy):
    x0, x1 = max(0, cx - patch_hw), min(img_w, cx + patch_hw + 1)
    y0, y1 = max(0, cy - patch_hh), min(img_h, cy + patch_hh + 1)
    if x1 <= x0: x1 = x0 + 1
    if y1 <= y0: y1 = y0 + 1
    r_sum = g_sum = b_sum = count = 0
    for yy in range(y0, y1):
        for xx in range(x0, x1):
            r, g, b = pixels[xx, yy]
            r_sum += r; g_sum += g; b_sum += b
            count += 1
    return r_sum // count, g_sum // count, b_sum // count

all_frames = []
for frame in frames_rgb:
    pixels = frame.load()
    frame_colors = []
    for (x_rect, y_rect) in rect_positions:
        ix, iy = map_to_image(x_rect, y_rect)
        cx, cy = int(round(ix)), int(round(iy))
        cx = min(max(cx, 0), img_w - 1)
        cy = min(max(cy, 0), img_h - 1)
        frame_colors.append(average_patch(pixels, cx, cy))
    all_frames.append(frame_colors)

print(f"img size: {img_w}x{img_h}, frames: {frame_count}, patch: {patch_hw*2+1}x{patch_hh*2+1}")

# --- Emit a C++ header with the sampled data ---
with open(OUT_PATH, "w") as f:
    f.write("#ifndef RICKROLL_DATA_H\n#define RICKROLL_DATA_H\n\n")
    f.write("// Generated by scripts/convert_gif.py from rik.gif. Regenerate after\n")
    f.write("// replacing rik.gif: python3 scripts/convert_gif.py\n")
    f.write("// Each entry is one LED's (r,g,b) for that frame, in the exact same pixel-index\n")
    f.write("// order as the hex grid (see ledgraph.h's AxialAccess), sampled by averaging a\n")
    f.write("// small patch of the source frame around that pixel's mapped image position.\n")
    f.write(f"#define RICKROLL_FRAME_COUNT {frame_count}\n")
    f.write(f"#define RICKROLL_FRAME_MS 50\n\n")
    f.write(f"static const uint8_t kRickRollFrames[RICKROLL_FRAME_COUNT][{LED_COUNT}][3] = {{\n")
    for fi, frame_colors in enumerate(all_frames):
        f.write("  {")
        for i, (r, g, b) in enumerate(frame_colors):
            f.write(f"{{{r},{g},{b}}}")
            if i != len(frame_colors) - 1:
                f.write(",")
        f.write("},\n" if fi != frame_count - 1 else "}\n")
    f.write("};\n\n#endif\n")

print("wrote", OUT_PATH, os.path.getsize(OUT_PATH), "bytes")
